#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.
set -x
export POSTGRESQL_PWD=$OPENSHIFT_POSTGRESQL_DB_PASSWORD
psql --host=$OPENSHIFT_POSTGRESQL_DB_HOST --port=$OPENSHIFT_POSTGRESQL_DB_PORT --user=$OPENSHIFT_POSTGRESQL_DB_USERNAME $OPENSHIFT_APP_NAME < $OPENSHIFT_REPO_DIR/src/main/resources/create-tables.sql